name: Build and Test Prerelease

on:
  release:
    types: [prereleased]

#on:
  #push:
   # tags:
   #  - '[0-9]+.[0-9]+.[0-9]'
   #  - '[0-9]+.[0-9]+.[0-9]+_[0-9]'
    
env:
  USERNAME: ${{secrets.QUSERNAME}}
  PASSWORD: ${{secrets.QPASSWORD}}
  QREPOURL: ${{secrets.QREPOURL}}

jobs:
  check_tag:
    runs-on: ubuntu-latest
    outputs:
      run_other_jobs: ${{ steps.check-tag.outputs.run_jobs }}
    steps:
      - name: check tag
        id: check-tag
        run: |
          echo ${{ github.ref }}
          if ${{ github.ref }} =~ ^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]$ || ${{ github.ref }} =~ ^refs\/tags\/[0-9]+\.[0-9]+\.[0-9]+\_[0-9]{3}$; then
            echo "::set-output name=run_jobs::true"
          fi
 

  build:
    needs: [check_tag]
    if: needs.check_tag.outputs.run_other_jobs == 'true'
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image 
        #if: needs.check_tag.outputs.run_other_jobs == 'true'
        run: |
          docker build . --file Dockerfile --rm -t "${QREPOURL}:${GITHUB_SHA}"
          docker login -u="${USERNAME}" -p="${PASSWORD}" quay.io
          docker push "${QREPOURL}:${GITHUB_SHA}"
 
