name: Build and Test Prerelease

on:
  release:
    types: [prereleased]
    
env:
  USERNAME: ${{secrets.QUSERNAME}}
  PASSWORD: ${{secrets.QPASSWORD}}
  QREPOURL: ${{secrets.QREPOURL}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --rm -t "${QREPOURL}:${GITHUB_SHA}"
        docker login -u="${USERNAME}" -p="${PASSWORD}" quay.io
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker push "${QREPOURL}:${VERSION}"
