name: Build and Test Prerelease

on:
  release:
    types: [prereleased]

#on:
  #push:
   # tags:
   #  - '[0-9]+.[0-9]+.[0-9]'
   #  - '[0-9]+.[0-9]+.[0-9]+_[0-9]'
    
env:
  USERNAME: ${{secrets.QUSERNAME}}
  PASSWORD: ${{secrets.QPASSWORD}}
  QREPOURL: ${{secrets.QREPOURL}}

jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Check Tag
        id: check-tag
        run: |
          echo ${{ steps.get_version.outputs.VERSION }}
          echo "Hello World"
          if [[ ${{ steps.get_version.outputs.VERSION }} =~ ^[0-9]+.[0-9]+.[0-9]+$ || ${{ steps.get_version.outputs.VERSION }} =~ ^[0-9]+.[0-9]+.[0-9]+_[0-9]{3}$ ]]; then
            echo ::set-output name=match::true
          fi
 

  build:
    needs: [check_tag]
    if: steps.check-tag.outputs.match == 'true'
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image 
        #if: needs.check_tag.outputs.run_other_jobs == 'true'
        run: |
          docker build . --file Dockerfile --rm -t "${QREPOURL}:${GITHUB_SHA}"
          docker login -u="${USERNAME}" -p="${PASSWORD}" quay.io
          docker push "${QREPOURL}:${GITHUB_SHA}"
 
