name: Build and Test Prerelease

on:
  push:
    tags:
     - '[0-9]+.[0-9]+.[0-9]'
     - '[0-9]+.[0-9]+.[0-9]+_[0-9]'
    
env:
  USERNAME: ${{secrets.QUSERNAME}}
  PASSWORD: ${{secrets.QPASSWORD}}
  QREPOURL: ${{secrets.QREPOURL}}

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event.release.prerelease
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --rm -t "${QREPOURL}:${GITHUB_SHA}"
        docker login -u="${USERNAME}" -p="${PASSWORD}" quay.io
        docker push "${QREPOURL}:${GITHUB_SHA}"
